# Generated by Django 4.0.2 on 2022-03-31 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_tlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlist',
            name='fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='work.test'),
            preserve_default=False,
        ),
    ]
