# Generated by Django 4.0.2 on 2022-03-31 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_alter_tlist_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tlist',
            old_name='fk',
            new_name='fok',
        ),
    ]
