# Generated by Django 4.0.2 on 2022-03-31 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_alter_tlist_fok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlist',
            name='fok',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.test'),
        ),
    ]
