# Generated by Django 4.0.2 on 2022-03-31 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_alter_tlist_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tlist',
            old_name='fok',
            new_name='user',
        ),
    ]
