# Generated by Django 4.0.2 on 2022-03-31 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_rename_fok_tlist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tlist',
            old_name='user',
            new_name='fok',
        ),
    ]
