# Generated by Django 4.0.2 on 2022-03-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_alter_tlist_fok'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
