# Generated by Django 4.0.2 on 2022-04-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0017_alter_tlist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlist',
            name='status',
            field=models.CharField(choices=[('C', 'COMPLETED'), ('P', 'PENDING')], max_length=15),
        ),
    ]
